Add controllers
MarinaVolk/java-shareit pull request #1
Opened 2023-06-30 10:05 UTC by MarinaVolk

2023-06-30 15:52 UTC, TomattmanYandex requested changes
ПРивет, коменты в коде

2023-06-30 15:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +package ru.practicum.shareit.booking.model;
При разбиении пакетов по фичам, обычно не создают подпакеты под каждый тип классов, 
есть пакет booking и в нем будут все классы которые к нему относятся

2023-06-30 15:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> getItemsListByOwnerId(@RequestHeader(value = "X-Sharer-User-Id", required = false, defaultValue = "-1") Long userId) {
почему дефолтное значение -1
что будет если прийдет пользователь с id -1 ссылочные типы могут иметь значение null следует использовать его

2023-06-30 15:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +import lombok.Data;
снова то же самое что в букинге про пакеты

2023-06-30 15:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/repository/ItemInMemoryRepository.java
> +package ru.practicum.shareit.item.repository;/* # parse("File Header.java")*/
и снова про пакеты
все больше добавлять не буду, но поправить надо будет

2023-06-30 15:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    ItemRepository itemRepository = new ItemInMemoryRepository();
1) модификаторы доступа
2) мы не создаем зависимости через конструктор

2023-06-30 15:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserValidator.java
> +public class UserValidator {
валидаторы кстати можно тоже сделать компонентами и инжектить

2023-07-01 15:04 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +package ru.practicum.shareit.booking.model;
Исправлено

2023-07-01 15:06 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> getItemsListByOwnerId(@RequestHeader(value = "X-Sharer-User-Id", required = false, defaultValue = "-1") Long userId) {
Исправлено

2023-07-01 15:07 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +import lombok.Data;
Исправлено

2023-07-01 15:08 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/item/repository/ItemInMemoryRepository.java
> +package ru.practicum.shareit.item.repository;/* # parse("File Header.java")*/
Исправлено

2023-07-01 15:22 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    ItemRepository itemRepository = new ItemInMemoryRepository();
Исправлено

2023-07-01 15:22 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/user/UserValidator.java
> +public class UserValidator {
Исправлено

2023-07-02 10:27 UTC, TomattmanYandex approved these changes
один комент оставил, но это можно поправить к следующему спринту

2023-07-02 10:27 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    @Autowired
у спринга есть несколько способов инжекта зависимостей, например по конструктору или аннотацией autowired лучше использовать один из 
тих двух способов
добавить всем зависимостям моификатор final 
тогда @RequiredArgsConstructor создаст конструктор с ними, и это заинжектит зависимости даже без @Autowired

2023-07-03 10:12 UTC, merged