Add bookings
MarinaVolk/java-shareit pull request #2
Opened 2023-07-26 13:55 UTC by MarinaVolk

2023-07-27 08:07 UTC, TomattmanYandex requested changes
Привет, я накаидал коментариев, множество однотипных проблем по ним связанных, так что стоит для начала это все переделать,

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booker.java
> +public class Booker {
Зачем этот класс?

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "item_id")
Для классов моделей при использованиии Jpa
Для ссылок на другие таблицы используем переменную с типом данных из другой таблицы, и аннотации типа @OneToMany @ManyToOne @ManyToMany

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private String itemName;
это мы получаем из объекта item оно нам тут не надо

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "booker_id")
а это переменная типа User

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                 @RequestBody Booking booking) {
на уровне контроллеров мы работает с Dto на получение и возврат

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        Optional.ofNullable(booking.getId()).ifPresent(bookingDto::setId);
интересно, но смысл если id равно null то оно и при проставении сеттером им останется
bookingDto.setId(booking.getId())

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public BookingDto addBooking(Booking booking, Long bookerId) {
Тут тоже лучше в параметрах использовать dto

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!userService.userExistsById(bookerId)) {
тут два момента
1) из сервиса лучше получить обьект (так мы сможем его переиспользовать если он нам еще будет нужен, без дополнительных запросов)
2) в самом методе getById стоит сделать проверку на null или empty и тут уже не делать ее

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!itemService.itemExistsById(booking.getItemId())) {
вот тут проблема что я описал выше, тебе надо сделать по одному объекту несколько проверок, и для каждой из них делается запрос в базу данных
а если бы был использован getById то был бы один запрос а провеяли бы уже объект из памяти

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        bookingDto.getItem().setName(itemService.getItemById(bookingDto.getItem().getId()).getName());
и тут снова, могли бы использовать из памяти

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!bookingDto.getBooker().getId().equals(bookerId)
тут снова те же проблемы

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!bookingDto.getBooker().getId().equals(bookerId)
плюс в зависимости от того как ты настроишь переменную item в букинг, возможно не надо будет делаьть второй запрос в базу, ти при получении букинга итем будет уже в нем

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingValidator.java
> +    private void startValidator(LocalDateTime start) throws ValidationException {
часть Validator это имя для класса, геттера или сеттера. А это просто метод, поэтому лучше validate

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/ItemForResponse.java
> +public class ItemForResponse {
ItemResponseDto будет лучше именем

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +    private Long itemId;
аналогично про переменные в модели

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/Item.java
>      private Long ownerId;
аналогично про тип переменных

2023-07-27 08:07 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +package ru.practicum.shareit.item;/* # parse("File Header.java")*/
так как комментарии - это подфункционал айтемов, можно(лучше) создать подпакет в пакете item для хранения всего что с ними связано, будет проще восприниматься

2023-07-29 19:02 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/Booker.java
> +public class Booker {
Класс удалён.

2023-07-29 19:04 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "item_id")
Изменено на:
@ManyToOne
    private Item item;

2023-07-29 19:04 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    private String itemName;
Удалено.

2023-07-29 19:05 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "booker_id")
Изменено на:
@ManyToOne
    private User booker;

2023-07-29 19:06 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                 @RequestBody Booking booking) {
Изменено на Dto.
public BookingDto addBooking(@RequestHeader("X-Sharer-User-Id") Long bookerId,
                                 @RequestBody BookingDto booking)

2023-07-29 19:08 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    public BookingDto addBooking(Booking booking, Long bookerId) {
Изменено на Dto:
public BookingDto addBooking(BookingDto booking, Long bookerId)

2023-07-29 19:13 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/BookingValidator.java
> +    private void startValidator(LocalDateTime start) throws ValidationException {
Переименовано.

2023-07-29 19:14 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/ItemForResponse.java
> +public class ItemForResponse {
Переименовано.

2023-07-29 19:14 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +    private Long itemId;
Исправлено.

2023-07-29 19:15 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/item/Item.java
>      private Long ownerId;
Исправлено на:
@ManyToOne
    private User owner;

2023-07-29 19:17 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +package ru.practicum.shareit.item;/* # parse("File Header.java")*/
Создано.

2023-07-29 20:08 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!bookingDto.getBooker().getId().equals(bookerId)
Исправлено. Сделан запрос: item = itemService.getItemById(), затем использован item.

2023-07-29 20:10 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!userService.userExistsById(bookerId)) {
Исправлено:
Сначала получены объекты, потом они переиспользованы. Лишние проверки удалены (присутствуют в  getById).
UserDto booker = userService.getUserById(bookerId);
ItemDto item = itemService.getItemById(booking.getItemId());

2023-07-29 20:11 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!itemService.itemExistsById(booking.getItemId())) {
Исправлено.

2023-07-29 20:11 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        bookingDto.getItem().setName(itemService.getItemById(bookingDto.getItem().getId()).getName());
Исправлено.

2023-07-29 20:26 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        Optional.ofNullable(booking.getId()).ifPresent(bookingDto::setId);
Исправлено.

2023-07-30 08:06 UTC, TomattmanYandex requested changes
Есть стоит немного обновить

2023-07-30 08:06 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @ManyToOne(cascade = CascadeType.MERGE)
чаще при использовании такой аннотации добавляют так же через какие поля происходит связь

и да, надеюсь ты понимаешь что значат CascadeType

2023-07-30 08:06 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!item.getAvailable()) {
эту и следующую проверку можно вынести в отдельный метод, так как эо по сути валидация айтема, и тогда код будет читаться гораздо лучше

2023-07-30 08:06 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/BookingForItem.java
> +public class BookingForItem {
Если это дто, то так и следует отобразить в имени  переменной

2023-07-30 08:06 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/Item.java
> +    @Column(name = "request_id")
про это уже писал в прошлой проверке, если ссылка на другую таблицу то используем обьект
Хотя ладно здесь еще нету функциональности реквестов, так что пока так нормально

2023-07-30 08:06 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemDtoForGet.java
> +public class ItemDtoForGet {
названия классов конечно очень странные
ведь проще как
Если для ответа, то itemResponseDto
для запроса itemRequestDto
если полные обьекты содержатся то itemRequestFullDto ItemResponseFullDto
если только id то ItemRequestShortDto itemREsponseShortDto

кстати это касается и BookingForItem скорее всего это просто дто какого то типа, которая может использоваться не только для айтемов но и в другимх местах

2023-07-30 16:01 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (!item.getAvailable()) {
Вынесено в метод validateItem(ItemDto item, Long bookerId).

2023-07-30 16:30 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/item/BookingForItem.java
> +public class BookingForItem {
Переименовано в BookingShortDto.

2023-07-30 16:31 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/item/ItemDtoForGet.java
> +public class ItemDtoForGet {
Классы переименованы в ItemResponseFullDto, ItemResponseShortDto, BookingShortDto.

2023-07-31 09:14 UTC, TomattmanYandex approved these changes
Принято

2023-07-31 09:14 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @ManyToOne
тут не было ошибки, разве что стоило добавить по каким полям идет мапипнг, а второй вопрос был только чтобы убедиться что ты уверена что делаешь)

2023-07-31 10:29 UTC, merged