Add item requests
MarinaVolk/java-shareit pull request #3
Opened 2023-09-03 12:32 UTC by MarinaVolk

2023-09-04 08:38 UTC, TomattmanYandex requested changes
Привет, работа хорошая, по основной части всякие мелочи которые стоит поправить, а вот по тестам надо переделать, во первых переделать существующие тесты, во вторых не хватает юнит тестов, тестов базы, и тестов json-> dto

2023-09-04 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                         @RequestParam(required = false, defaultValue = "20") Integer size) {
на это поле можно также накинуть валидацию,  чтобы было меньше ошибок, и на предыдущее тоже

2023-09-04 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Pageable pageable = PageRequest.of(from / size, size, Sort.by("start").descending());
у тебя логика по созданию Pagable будет везде одинаковая , и проверка скорее всего тоже
а в создании Pagable заложено немного логики,  и если вдруг придёт требование о том, что например первым параметром должен приходить номер страницы, а не номер позиции, то в каждом месте, где создается объект PAgable придётся менять код
Поэтому лучше создать утильный класс который будет иметь статический метод по созданию Pagable и везде его использовать
Также туда можно подвигать проверку двух параметров, ну или как я уже написал выше валидировать аннотацией на уровне контроллера

2023-09-04 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                .map(BookingMapper::toDto)
лучше в маппере создать метод toDto который будет принимать лист букингов (перегрузить существующий метод) и там делать то же что и тут превращать в стрим, и каждый мапить существующим методом, так получится что за маппинг букинга будет отвечать только один класс

2023-09-04 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    Page<Item> searchItemForRentByText(String text, Pageable pageable);
стоит удалить пустую строчку выше, ведь @Query относится к этому методу

2023-09-04 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    @Column(name = "requestor_id")
в обьектах мы используем сами обьекты а не их id 
смотри аннотации @ManyToOne @OneToMany и другие

2023-09-04 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequestDto.java
> +    private LocalDateTime created = LocalDateTime.now();
тут лучше не проставлять значение
пусть оно проставляется только на уровне сущности базы данных, меньше потенциальных ошибок

2023-09-04 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        if (!userService.userExistsById(requestorId)) {
можно использовать метод юзер сервиса  который ищет по id (он все равно кидает эту ошибку) и если никого найдено не будет то сам бросит ошибку

2023-09-04 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        Pageable pageable = PageRequest.of(page, size, Sort.by("created").descending());
тут будет то же самое про Pagable что писал выше только тут еще проверки нету

2023-09-04 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +
как то много лишних пропусков строк

2023-09-04 08:38 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/request/ItemRequestValidator.java
> +    private void itemRequestDescriptionValidator(String description) {
не лучше ли повесить аннотацию на поле в DTO

2023-09-04 08:38 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    ObjectMapper mapper;
Лучше в тестах на поля тоже добавлять модификаторы доступа, чтобы не забывать их в других случаях

2023-09-04 08:38 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void addBookingShouldAddBooking() throws Exception {
стоит также добавить пару негативных кейсов, но скорее лучше это сделать в интеграционных тестах

2023-09-04 08:38 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    void addBookingShouldCreateBooking() {
я не могу понять что проверяет этот тест, слишком много действий, обычно делается маленький тест на каждый случай, например будет один тест на то , что все успешно, один тест на то, что упадет ошибка, один тест на то, что упадет ошибка при других условиях, и т.д.
 стоит этот тест разбить на несколько тестов

очень часто тесты делают в структуре Given-When-Then
тестовый метод комментариями разделяют на три части 
//given 
тут происходит предварительная настройка, создание нужных объектов и подготовка теста
//when 
тут обычно вызывают тестируемы метод
//then 
тут происходит проверка результата

\та структура позволяет создать хороший читаемый тест

2023-09-17 16:53 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                         @RequestParam(required = false, defaultValue = "20") Integer size) {
Добавлено.

2023-09-17 16:55 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        Pageable pageable = PageRequest.of(from / size, size, Sort.by("start").descending());
Добавила класс PageUtil с методами createPage() и checkPageParameters() для этих целей.

2023-09-17 16:56 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                .map(BookingMapper::toDto)
Добавила в маппер метод:
public static List<BookingDto> toDtoList (List<Booking> bookings), который возвращает List<BookingDto>

2023-09-17 16:58 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    Page<Item> searchItemForRentByText(String text, Pageable pageable);
Исправлено.

2023-09-17 16:58 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    @Column(name = "requestor_id")
Исправлено.

2023-09-17 16:59 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/request/ItemRequestDto.java
> +    private LocalDateTime created = LocalDateTime.now();
Исправлено.

2023-09-17 17:00 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        if (!userService.userExistsById(requestorId)) {
Удалено, оставлен метод юзер сервиса - getById().

2023-09-17 17:00 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        Pageable pageable = PageRequest.of(page, size, Sort.by("created").descending());
Исправлено.

2023-09-17 17:00 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +
Исправлено.

2023-09-17 17:00 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/request/ItemRequestValidator.java
> +    private void itemRequestDescriptionValidator(String description) {
Аннотацию добавила.

2023-09-17 17:00 UTC, MarinaVolk commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    ObjectMapper mapper;
Добавлено.

2023-09-17 22:15 UTC, MarinaVolk commented on src/test/java/ru/practicum/shareit/booking/BookingServiceImplTest.java
> +    void addBookingShouldCreateBooking() {
Исправлено.

2023-09-18 09:35 UTC, TomattmanYandex requested changes
Привет, с тестами еще надо поработать

2023-09-18 09:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                         @RequestParam(required = false, defaultValue = "20") Integer size) {
Я имел ввиду from и size что будет если что то из этого будет 0 или отрицательным?

2023-09-18 09:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                         @RequestParam(required = false, defaultValue = "20") Integer size) {
и как будет валидироваться строка и число?

2023-09-18 09:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        checkPageParameters(from, size);
проверка параметров pagable   всегда будет идти вместе с созданием объекта pagable , почему бы не засунуть проверку в сам метод создания?

2023-09-18 09:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/PageUtil.java
> +    public static void checkPageParameters(Integer from, Integer size) {
то о чем писал чуть выше, можно сделать вызов этого метода перед строчками 17 и 21 и тогда при создании уже не надо будет дергать этот метод

2023-09-18 09:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/PageUtil.java
> +        int page = from / size;
два метода которые делают почти одно и тоже но реализованы по разному, выглядит странно

2023-09-18 09:35 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        List<BookingDto> bookingDtos = bookings
еще хороший способ как это реализовать
сделать точно так же, но не создавать дополнительную переменную
return а потом все что после знака равно

2023-09-18 09:35 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingTest.java
> +    BookingValidator validator;
я писал еще при прошлой проверке, следует добавлять модификаторы доступа

2023-09-18 09:35 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingTest.java
> +    public void createInvalidBookingsTest() {
также про это писал,
стоит сделать отдельный тест под каждую проверку
отдельный тест на отсутствие начала аренды, отдельный тест на начало аренды в прошлом и т.д
и имена методов могут быть таким
isValid_throwException_startDateNotPresented
isValid_throwException_startDateIsInPast
и т.д.

2023-09-18 09:35 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingDtoJsonTest.java
> +    JacksonTester<BookingDto> json;
модификаторы

2023-09-18 09:35 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    void verifyRepository() {
что проверяет этот тест?
у тебя есть в репозитории несколько костомных методов, следует проверить что каждый из них работает как надо
т.е. заполнили базу а потом отдельный тест на каждый метод репозитория, с проверкой что он возвращает то что надо, и тестируем именно методы кастомные, стандартным можно и поверить)

2023-09-18 09:35 UTC, TomattmanYandex commented on src/test/java/ru/practicum/shareit/booking/BookingTest.java
> +public class BookingTest {
не понятно что тестирует этот класс, по коду вижу что валидацию, но в имени не вижу

2023-09-18 18:20 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                                         @RequestParam(required = false, defaultValue = "20") Integer size) {
Добавила аннотации @Min(0) - для Integer from  и  @Min(1) для Integer size. Также в PageUtils присутствует метод checkPageParameters(), который тоже проверяет, чтобы параметры были такими.

2023-09-18 18:25 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        checkPageParameters(from, size);
Перенесено.

2023-09-18 18:26 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/PageUtil.java
> +    public static void checkPageParameters(Integer from, Integer size) {
Да, отличное предложение) перенесено)

2023-09-18 18:44 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/PageUtil.java
> +        int page = from / size;
Сделала один метод:  public static Pageable createPage(Integer from, Integer size, String sortBy)

2023-09-18 18:45 UTC, MarinaVolk commented on src/main/java/ru/practicum/shareit/booking/BookingMapper.java
> +        List<BookingDto> bookingDtos = bookings
Переделано.

2023-09-18 18:47 UTC, MarinaVolk commented on src/test/java/ru/practicum/shareit/booking/BookingTest.java
> +    BookingValidator validator;
Добавлено.

2023-09-18 18:51 UTC, MarinaVolk commented on src/test/java/ru/practicum/shareit/booking/BookingDtoJsonTest.java
> +    JacksonTester<BookingDto> json;
Добавлено.

2023-09-18 18:53 UTC, MarinaVolk commented on src/test/java/ru/practicum/shareit/booking/BookingTest.java
> +public class BookingTest {
Скорректировано.

2023-09-18 19:17 UTC, MarinaVolk commented on src/test/java/ru/practicum/shareit/booking/BookingTest.java
> +    public void createInvalidBookingsTest() {
Скорректировано.

2023-09-18 21:17 UTC, MarinaVolk commented on src/test/java/ru/practicum/shareit/booking/BookingRepositoryTest.java
> +    void verifyRepository() {
Переделано: в тестах BookingRepositoryTest, ItemRepositoryTest тестирую только кастомные методы (после заполнения базы). 
Названия тестов скорректировала: findByBookerId_BookingsListProvidedWhenRequestedByBookerId(),  findByItemId_BookingsListProvidedWhenRequestedByItemId()  и т.д.

2023-09-19 15:34 UTC, TomattmanYandex approved these changes
Принято

2023-09-20 19:02 UTC, merged